title: Your awesome title
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description. # the subpath of your site, e.g. /blog
url: "http://localhost:2107" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
include: ['_pages']
exclude: ['.git', 'Gemfile', 'Gemfile.lock', 'gulpfile.js', 'package-lock.json', 'package.json', '.gitignore', '.forestry', '.sass-cache', 'node_modules']
sass:
  style: compressed
  sass_dir: _sass
permalink: /:title
paginate: 5
plugins:
  - jekyll-feed
  - jekyll-menus

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
